---
title: "MGT Research Prophet Part"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries
```{r cars}
library(quantmod)
library(Rcpp)
library(rlang)
library(prophet)
library(dplyr)
library(Rfast)
library(tseries)
library(fGarch)

```

## Data and Factors

You can also embed plots, for example:

```{r pressure, echo=FALSE, warning=FALSE}

coins <- c("BTC-USD", "BNB-USD", "ETH-USD", "XRP-USD", "LTC-USD", "DOGE-USD", "UUP", "SPY", "USO")
getSymbols(coins, from = "2018-01-01", to = "2021-12-31", src = "yahoo")

df = data.frame(diff(log(`BTC-USD`[,6]))[-1], diff(log(`BNB-USD`[,6]))[-1], 
                diff(log(`ETH-USD`[,6]))[-1], diff(log(`XRP-USD`[,6]))[-1],
                diff(log(`LTC-USD`[,6]))[-1])

df_side = data.frame(`USO`[,6][-1], `UUP`[,6][-1])
df_side$date = rownames(df_side)
df_extra = as.data.frame(`SPY`[,6])
df_extra$date = rownames(df_extra)
df_side = left_join(df_side, df_extra, by = "date")
length(df_side[,1])
rownames(df) <- index(`BTC-USD`)[-1]
colnames(df) <- c("BTC", "BNB", "ETH", "XRP", "LTC")
tail(df_side)


```


```{r}
plot_prophet_log_side <- function(input, days){
  training_len = (length(input$date)-days)
  print(training_len)
  df1 = head(input, training_len)
  
  #colnames(df1) <- c('y','ds')
  colnames(df1) <- c('y','ds','USO','UUP','SPY')

  init_model = prophet(daily.seasonality = F, seasonality.mode = "multiplicative")
  #init_model = prophet(df = df1, daily.seasonality = F,seasonality.mode = "multiplicative")
  #add regressors
  init_model = add_regressor(init_model, 'USO', mode = "additive")
  init_model = add_regressor(init_model, 'UUP', mode = "additive")
  init_model = add_regressor(init_model, 'SPY', mode = "additive")

  init_model = fit.prophet(init_model, df1)
  
  future = make_future_dataframe(init_model, periods = days)
  future$USO = input$USO
  future$UUP = input$UUP
  future$SPY = input$SPY

  forecast = predict(init_model, future)
  #plot(forecast$yhat)
  
  #test_data = input[,1][(training_len+1):length(input$date)]
  #test_data = diff(log(test_data))[-1]
  
  #print(forecast)
  predict = tail(forecast, days) #forecast$yhat[(training_len+1):length(input$date)]
  predict_data = data.frame(predict$yhat,as.character(predict$ds))
  #predict_data = diff(log(predict_data))[-1]
  #plot(init_model, forecast)
  return(predict_data)
  
  #print(mean((predict_data - test_data)^2))
  #prophet_plot_components(init_model, forecast)
  
  #Classification:
  #matrix = to_matrix(predict_data,test_data)
  #print((matrix[1,1]+matrix[2,2])/days)
  #print(matrix)
  
  #plot(test_data, type = 'l', col = 'red')
  #lines(predict_data)

}
```

```{r}
rolling_prophet = function(input, days, test, garch){
  orig_input_len = length(input$date)-days
  test_data = input[,1][(orig_input_len+1):length(input$date)]
  #test_data = diff(log(test_data))[-1]
  predict = c()
  predict_date = c()
  
  step = days/10
  for (i in c(1:(days/step))){
    temp = plot_prophet_log_side(head(input, (orig_input_len+(i*step))),step)
    predict = c(predict, temp[,1])
    predict_date = c(predict_date, temp[,2])
  }
  #predict = diff(log(predict))[-1]
  #test_data = diff(log(test[1:100]))[-1]
  
  predict_frame = data.frame(predict, predict_date)
  colnames(predict_frame) = c("pred","ds")
  predict_frame[predict_frame < 0] <- NA

  test_frame = data.frame(test[,1], rownames(test))
  colnames(test_frame) = c("test","ds")
  compare <- na.omit(left_join(predict_frame, test_frame, by=c("ds")))
  print(mean((compare$pred - compare$test)^2))
  #print(mean((predict - test_data)^2))
  
  #test_diff = rowprods(matrix((diff(test[1:100])[-1]+1), ncol = 7, byrow = TRUE))-1
  #predict_diff = rowprods(matrix((diff(predict)[-1]+1),ncol = 7, byrow = TRUE))-1
  #print(test_diff)
  #Classification:
  #matrix = to_matrix(predict,test)
  #print((matrix[1,1]+matrix[2,2])/(days))
  #print(matrix)  
  #predict_diff = diff(log(compare$pred))[-1]
  #text_diff =  diff(log(compare$test))[-1]
  
  plot(compare$pred, type = 'l', col = 'red')
  lines(compare$test, col = 'blue')
  #lines(garch[1:78])
}
```

```{r}
to_matrix = function(list_pred, list_test){
  matrix = data.frame(down = c(0,0), up = c(0,0))
  rownames(matrix) = c("down", "up")
  for (i in 1:length(list_pred)){
    if (list_pred[i] > 0 & list_test[i] > 0){
      matrix[2,2] = matrix[2,2] + 1
    }
    else if(list_pred[i] > 0 & list_test[i] < 0){
      matrix[2,1] = matrix[2,1] + 1
    }
    else if(list_pred[i] < 0 & list_test[i] > 0){
      matrix[1,2] = matrix[1,2] + 1
    }
    else if(list_pred[i] < 0 & list_test[i] < 0){
      matrix[1,1] = matrix[1,1] + 1
    }
  }
  return(matrix)
}
```

```{r}
rolling_garch = function(input,days, test){
  orig_input_len = length(input$date)-days
  train_data = diff(log(input[,1]))[-1]
  predict = c()
  step = days/50
  for (i in c(1:(days/step))){
    train_data_set=head(train_data, (orig_input_len+((i-1)*step)))
    m = garchFit(formula=~garch(1,1), data = train_data_set, trace=F)
    predict = c(predict, predict(m,step)$standardDeviation)
    #plot(m)
  }
  return(predict)
  #print(orig_input_len)
  #print(mean((predict - test[1:100])^2))
  
  #plot(test[1:100], type = 'l', col = 'red')
  #lines(predict)
}
```

```{r}
#bitcoin
#BTC = as.data.frame(diff(log(`BTC-USD`[,6]))[-1])
BTC = as.data.frame(`BTC-USD`[,6])
BTC_test = tail((BTC), 144)
#BTC = as.data.frame(`BTC-USD`[,6][-1])
BTC$date = rownames(BTC)
BTC <- na.omit(left_join(BTC, df_side, by=c("date")))
#BTC_garch = rolling_garch(BTC, 100, BTC_test)
rolling_prophet(BTC, 100, BTC_test, BTC_garch)
#plot(plot_prophet_log(BTC[,c(1,2)],100))

#rolling_garch(BTC, 100, BTC_test)

#BNB
#BNB = as.data.frame(diff(log(`BNB-USD`[,6]))[-1])
BNB = as.data.frame(`BNB-USD`[,6])
BNB_test = tail(BNB, 144)
BNB$date = rownames(BNB)
BNB <- na.omit(left_join(BNB, df_side, by=c("date")))
#BNB_garch = rolling_garch(BNB, 100, BNB_test)
rolling_prophet(BNB, 100, BNB_test, BNB_garch)

#ETH
#ETH = as.data.frame(diff(log(`ETH-USD`[,6]))[-1])
ETH = as.data.frame(`ETH-USD`[,6])
ETH_test = tail(ETH, 144)
ETH$date = rownames(ETH)
ETH <- na.omit(left_join(ETH, df_side, by=c("date")))
#ETH_garch = rolling_garch(ETH, 100, ETH_test)
rolling_prophet(ETH, 100, ETH_test, ETH_garch)

#XRP
#XRP = as.data.frame(diff(log(`XRP-USD`[,6]))[-1])
XRP = as.data.frame(`XRP-USD`[,6])
XRP_test = tail(XRP, 144)
XRP$date = rownames(XRP)
XRP <- na.omit(left_join(XRP, df_side, by=c("date")))
#XRP_garch = rolling_garch(XRP, 100, XRP_test)
rolling_prophet(XRP, 100, XRP_test, XRP_garch)

#LTC
#LTC = as.data.frame(diff(log(`LTC-USD`[,6]))[-1])
LTC = as.data.frame(`LTC-USD`[,6])
LTC_test = tail(LTC, 144)
LTC$date = rownames(LTC)
LTC <- na.omit(left_join(LTC, df_side, by=c("date")))
#LTC_garch = rolling_garch(LTC, 100, LTC_test)
rolling_prophet(LTC, 100, LTC_test, LTC_garch)

#DOGE
#DOGE = as.data.frame(diff(log(`DOGE-USD`[,6]))[-1])
DOGE = as.data.frame(`DOGE-USD`[,6])
DOGE_test = tail(DOGE, 144)
DOGE$date = rownames(DOGE)
DOGE <- na.omit(left_join(DOGE, df_side, by=c("date")))
#DOGE_garch = rolling_garch(DOGE, 100, DOGE_test)
rolling_prophet(DOGE, 100, DOGE_test, DOGE_garch)
```

